### ISSUE TITLE
能ping通背景图片api地址，但插件获取背景图失败

### ISSUE THREAD

**Issue by HL-Light** [lgc-NB2Dev/nonebot-plugin-picstatus#45]
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-picstatus/assets/116658416/0719d2a8-e247-405b-9300-69f48640bc1b)

```
`2024-04-11 14:52:38.339 | INFO     | nonebot:_run_matcher:406 - Event will be handled by Matcher(type='message', module=nonebot_plugin_picstatus.__main__, lineno=27)
2024-04-11 14:52:39.348 | ERROR    | nonebot_plugin_picstatus:get_bg:119 - Error when getting background, fallback to local
Traceback (most recent call last):

  File "/home/hg/onebot/bot/lib/python3.10/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/hg/onebot/bot/lib/python3.10/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
                 │    │     │                    └ <Request [b'GET']>
                 │    │     └ <function AsyncConnectionPool.handle_async_request at 0x7f9e23db5ea0>
                 │    └ <AsyncHTTPProxy [Requests: 0 active, 0 queued | Connections: 0 active, 0 idle]>
                 └ <httpx.AsyncHTTPTransport object at 0x7f9dfc103430>
  File "/home/hg/onebot/bot/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/home/hg/onebot/bot/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
                     │          └ <function AsyncTunnelHTTPConnection.handle_async_request at 0x7f9e23db6e60>
                     └ <AsyncTunnelHTTPConnection [CONNECTION FAILED]>
  File "/home/hg/onebot/bot/lib/python3.10/site-packages/httpcore/_async/http_proxy.py", line 289, in handle_async_request
    connect_response = await self._connection.handle_async_request(
                             │    │           └ <function AsyncHTTPConnection.handle_async_request at 0x7f9e23db5000>
                             │    └ <AsyncHTTPConnection [CONNECTION FAILED]>
                             └ <AsyncTunnelHTTPConnection [CONNECTION FAILED]>
  File "/home/hg/onebot/bot/lib/python3.10/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/home/hg/onebot/bot/lib/python3.10/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
                   │    │        └ <Request [b'CONNECT']>
                   │    └ <function AsyncHTTPConnection._connect at 0x7f9e23db5090>
                   └ <AsyncHTTPConnection [CONNECTION FAILED]>
  File "/home/hg/onebot/bot/lib/python3.10/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
                   │    │                │             └ {'host': '127.0.0.1', 'port': 7890, 'local_address': None, 'timeout': 10, 'socket_options': None}
                   │    │                └ <function AutoBackend.connect_tcp at 0x7f9e23da3490>
                   │    └ <httpcore._backends.auto.AutoBackend object at 0x7f9dfc103370>
                   └ <AsyncHTTPConnection [CONNECTION FAILED]>
  File "/home/hg/onebot/bot/lib/python3.10/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
                 │    │        └ <function AnyIOBackend.connect_tcp at 0x7f9e23dc5cf0>
                 │    └ <httpcore.AnyIOBackend object at 0x7f9dfc101300>
                 └ <httpcore._backends.auto.AutoBackend object at 0x7f9dfc103370>
  File "/home/hg/onebot/bot/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    with map_exceptions(exc_map):
         │              └ {<class 'TimeoutError'>: <class 'httpcore.ConnectTimeout'>, <class 'OSError'>: <class 'httpcore.ConnectError'>, <class 'anyio...
         └ <function map_exceptions at 0x7f9e243412d0>
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
    │    │   │     │    │      └ <traceback object at 0x7f9dfc175540>
    │    │   │     │    └ OSError('All connection attempts failed')
    │    │   │     └ <class 'OSError'>
    │    │   └ <method 'throw' of 'generator' objects>
    │    └ <generator object map_exceptions at 0x7f9dfc0127a0>
    └ <contextlib._GeneratorContextManager object at 0x7f9dfc1013c0>
  File "/home/hg/onebot/bot/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
          └ <class 'httpcore.ConnectError'>

httpcore.ConnectError: All connection attempts failed


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "<string>", line 29, in <module>
  File "/home/hg/onebot/bot/lib/python3.10/site-packages/nonebot/__init__.py", line 334, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x7f9e24be7c70>
  File "/home/hg/onebot/bot/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
    │       └ <function run at 0x7f9e22821900>
    └ <module 'uvicorn' from '/home/hg/onebot/bot/lib/python3.10/site-packages/uvicorn/__init__.py'>
  File "/home/hg/onebot/bot/lib/python3.10/site-packages/uvicorn/main.py", line 575, in run
    server.run()
    │      └ <function Server.run at 0x7f9e228211b0>
    └ <uvicorn.server.Server object at 0x7f9dc2d52bf0>
  File "/home/hg/onebot/bot/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f9e22821240>
           │       │   └ <uvicorn.server.Server object at 0x7f9dc2d52bf0>
           │       └ <function run at 0x7f9e25d479a0>
           └ <module 'asyncio' from '/usr/lib/python3.10/asyncio/__init__.py'>
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f9dc2d492a0>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/home/hg/onebot/bot/lib/python3.10/site-packages/nonebot_plugin_picstatus/templates/pw_render.py", line 85, in wrapped_func
    return await func(route, request)
                 │    │      └ <Request url='http://picstatus.nonebot/api/background' method='GET'>
                 │    └ <Route request=<Request url='http://picstatus.nonebot/api/background' method='GET'>>
                 └ <function _ at 0x7f9dc22d31c0>
  File "/home/hg/onebot/bot/lib/python3.10/site-packages/nonebot_plugin_picstatus/templates/pw_render.py", line 156, in _
    data = await get_bg()
                 └ <function get_bg at 0x7f9dc22d2830>
> File "/home/hg/onebot/bot/lib/python3.10/site-packages/nonebot_plugin_picstatus/bg_provider.py", line 117, in get_bg
    return await registered_bg_providers[config.ps_bg_provider]()
                 │                       │      └ 'gm'
                 │                       └ ConfigModel(superusers={'2053660167'}, nickname={'二光'}, proxy='http://127.0.0.1:7890', ps_template='default', ps_command=['运行...
                 └ {'gm': <function gm at 0x7f9dc22d24d0>, 'loli': <function loli at 0x7f9dc22d25f0>, 'lolicon': <function lolicon at 0x7f9dc22d...
  File "/home/hg/onebot/bot/lib/python3.10/site-packages/nonebot_plugin_picstatus/bg_provider.py", line 50, in gm
    (await cli.get("https://api.gumengya.com/Api/DmImg"))
           │   └ <function AsyncClient.get at 0x7f9e23dd13f0>
           └ <httpx.AsyncClient object at 0x7f9dfc1cab30>
  File "/home/hg/onebot/bot/lib/python3.10/site-packages/httpx/_client.py", line 1801, in get
    return await self.request(
                 │    └ <function AsyncClient.request at 0x7f9e23dd1000>
                 └ <httpx.AsyncClient object at 0x7f9dfc1cab30>
  File "/home/hg/onebot/bot/lib/python3.10/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
                 │    │    │             │                      └ <httpx._client.UseClientDefault object at 0x7f9e24264550>
                 │    │    │             └ <httpx._client.UseClientDefault object at 0x7f9e24264550>
                 │    │    └ <Request('GET', 'https://api.gumengya.com/Api/DmImg')>
                 │    └ <function AsyncClient.send at 0x7f9e23dd11b0>
                 └ <httpx.AsyncClient object at 0x7f9dfc1cab30>
  File "/home/hg/onebot/bot/lib/python3.10/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
                     │    └ <function AsyncClient._send_handling_auth at 0x7f9e23dd1240>
                     └ <httpx.AsyncClient object at 0x7f9dfc1cab30>
  File "/home/hg/onebot/bot/lib/python3.10/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
                     │    └ <function AsyncClient._send_handling_redirects at 0x7f9e23dd12d0>
                     └ <httpx.AsyncClient object at 0x7f9dfc1cab30>
  File "/home/hg/onebot/bot/lib/python3.10/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
                     │    │                    └ <Request('GET', 'https://api.gumengya.com/Api/DmImg')>
                     │    └ <function AsyncClient._send_single_request at 0x7f9e23dd1360>
                     └ <httpx.AsyncClient object at 0x7f9dfc1cab30>
  File "/home/hg/onebot/bot/lib/python3.10/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
                     │         │                    └ <Request('GET', 'https://api.gumengya.com/Api/DmImg')>
                     │         └ <function AsyncHTTPTransport.handle_async_request at 0x7f9e23dc68c0>
                     └ <httpx.AsyncHTTPTransport object at 0x7f9dfc103430>
  File "/home/hg/onebot/bot/lib/python3.10/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
         └ <function map_httpcore_exceptions at 0x7f9e2431b7f0>
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
    │    │   │     │    │      └ <traceback object at 0x7f9dfc17a580>
    │    │   │     │    └ ConnectError(OSError('All connection attempts failed'))
    │    │   │     └ <class 'httpcore.ConnectError'>
    │    │   └ <method 'throw' of 'generator' objects>
    │    └ <generator object map_httpcore_exceptions at 0x7f9dfc013990>
    └ <contextlib._GeneratorContextManager object at 0x7f9dfc1036a0>
  File "/home/hg/onebot/bot/lib/python3.10/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
          │          └ 'All connection attempts failed'
          └ <class 'httpx.ConnectError'>

httpx.ConnectError: All connection attempts failed`
```

**Comment by FalfaChino** [comment]
重试看看？
如果不行可以换一个 bg API 试试

**Comment by HL-Light** [comment]
目前全部测试了一遍访问不到，我用weget测试网络是没问题的
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-picstatus/assets/116658416/5f69971e-70e5-47e8-9ee4-c375ca3d1fb0)

**Comment by HL-Light** [comment]
我发现在启动时存在waring，不知道是否是这个发问题
```
04-12 00:45:56 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_picstatus"
/home/hg/onebot/bot/lib/python3.10/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
```

**Comment by lgc2333** [comment]
这大概是PicMenu插件引用的`fuzzywuzzy`库的的警告
