### ISSUE TITLE
无法获取背景图片，提示AttributeError: 'NoneType' object has no attribute 'json'

### ISSUE THREAD

**Issue by Dream-Rainy** [lgc-NB2Dev/nonebot-plugin-picstatus#46]
无法获取背景图片，错误日志如下
```
06-04 18:07:34 [ERROR] nonebot_plugin_picstatus | Error when getting background, fallback to local
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "/home/dreamrain/DreamRain-Bot/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/home/dreamrain/DreamRain-Bot/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/home/dreamrain/DreamRain-Bot/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/home/dreamrain/DreamRain-Bot/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/dreamrain/DreamRain-Bot/.venv/lib/python3.10/site-packages/nonebot_plugin_picstatus/templates/pw_render.py", line 85, in wrapped_func
    return await func(route, request)
  File "/home/dreamrain/DreamRain-Bot/.venv/lib/python3.10/site-packages/nonebot_plugin_picstatus/templates/pw_render.py", line 156, in _
    data = await get_bg()
> File "/home/dreamrain/DreamRain-Bot/.venv/lib/python3.10/site-packages/nonebot_plugin_picstatus/bg_provider.py", line 121, in get_bg    return await registered_bg_providers[config.ps_bg_provider]()
  File "/home/dreamrain/DreamRain-Bot/.venv/lib/python3.10/site-packages/nonebot_plugin_picstatus/bg_provider.py", line 90, in lolicon    url = resp.raise_for_status().json()["data"][0]["urls"]["original"]
AttributeError: 'NoneType' object has no attribute 'json'
```

**Comment by XieXiLin2** [comment]
https://github.com/lgc-NB2Dev/nonebot-plugin-picstatus/blob/ba92700eb73130157d35501cd6b2c95df5008377/.env.example#L34-L43

![](https://github.com/lgc-NB2Dev/nonebot-plugin-picstatus/assets/133548383/ebf9bc85-6b5b-42b1-a19d-597826dd81ea)

**Comment by Dream-Rainy** [comment]
尝试过了，在网络正常的情况下所有api均不可用
如故梦api和LoliApi均为`AttributeError: 'NoneType' object has no attribute 'content'`
以下为日志
```
06-04 20:13:47 [ERROR] nonebot_plugin_picstatus | Error when getting background, fallback to local
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "/home/dreamrain/DreamRain-Bot/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/home/dreamrain/DreamRain-Bot/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/home/dreamrain/DreamRain-Bot/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/home/dreamrain/DreamRain-Bot/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/dreamrain/DreamRain-Bot/.venv/lib/python3.10/site-packages/nonebot_plugin_picstatus/templates/pw_render.py", line 85, in wrapped_func
    return await func(route, request)
  File "/home/dreamrain/DreamRain-Bot/.venv/lib/python3.10/site-packages/nonebot_plugin_picstatus/templates/pw_render.py", line 156, in _
    data = await get_bg()
> File "/home/dreamrain/DreamRain-Bot/.venv/lib/python3.10/site-packages/nonebot_plugin_picstatus/bg_provider.py", line 121, in get_bg    return await registered_bg_providers[config.ps_bg_provider]()
  File "/home/dreamrain/DreamRain-Bot/.venv/lib/python3.10/site-packages/nonebot_plugin_picstatus/bg_provider.py", line 71, in loli
    .content
AttributeError: 'NoneType' object has no attribute 'content'
```

**Comment by Dream-Rainy** [comment]
相关配置文件
```
DRIVER=~fastapi+~httpx+~websockets
PROXY="http://127.0.0.1:7890"
PS_COMMAND=["运行状态", "状态", "status"]
PS_IGNORE_PARTS=["/snap"]
PS_IGNORE_DISK_IOS=["loop*"]
PS_BG_PROVIDER=lolicon
PS_BG_LOLICON_R18_TYPE=0
PS_USE_ENV_NICK=True
```
相关软件版本
NoneBot 2.3.1
PicStatus 2.0.0.post4
CPython 3.10.12
Ubuntu 22.04

**Comment by lgc2333** [comment]
尝试升级httpx版本
