### ISSUE TITLE
nickname无法使用？

### ISSUE THREAD

**Issue by YRRLYB** [lgc-NB2Dev/nonebot-plugin-picstatus#47]
我在.env里面设置了NICKNAME=buding。或者“buding”都会报错
08-16 14:30:46 [SUCCESS] nonebot | NoneBot is initializing...
Traceback (most recent call last):
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\config.py", line 235, in __call__
    env_val = json.loads(env_val)
  File "D:\bot\python\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\bot\python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\bot\python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\__init__.py", line 299, in init
    config = Config(
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\config.py", line 334, in __init__
    **__settings_self__._settings_build_values(
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\config.py", line 356, in _settings_build_values
    return deep_update(env_settings(), init_settings())
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\config.py", line 238, in __call__
    raise SettingsError(
nonebot.config.SettingsError: error parsing env var "nickname"他说环境变量出问题了？（

**Comment by XieXiLin2** [comment]
https://nonebot.dev/docs/appendices/config#nickname

NICKNAME 是一个类型为 list[str] 的变量。

**Comment by YRRLYB** [comment]
好的好的感谢解答
