### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [lgc-NB2Dev/nonebot-plugin-picstatus#52]
日志如下
```Python
11-03 14:08:52 [ERROR] nonebot | Error when running EventPreProcessors. Event ignored!
Traceback (most recent call last):
> File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\utils.py", line 238, in run_coro_with_catch
    return await coro
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_picstatus\misc_statistics.py", line 118, in
_
    recv_num[bot.self_id] += 1
KeyError: '257007689'
```

**Comment by lgc2333** [comment]
每条消息都有？还是偶发性的

**Comment by YuYue-Amatsuki** [comment]
> 每条消息都有？还是偶发性的

每条消息都有

**Comment by lgc2333** [comment]
什么情况下出现的？刚启动nb就有吗？还是bot断线重连后？

**Comment by lgc2333** [comment]
可以稳定复现吗？

**Comment by YuYue-Amatsuki** [comment]
> 什么情况下出现的？刚启动nb就有吗？还是bot断线重连后？

nb启动后bot接收消息后即抛出该错误

**Comment by lgc2333** [comment]
> 可以稳定复现吗？

**Comment by YuYue-Amatsuki** [comment]
> > 可以稳定复现吗？

可以 每次接受消息后都有该错误

**Comment by lgc2333** [comment]
请问你是用的适配器是？

**Comment by YuYue-Amatsuki** [comment]
> 请问你使用的适配器是？

onebotv11

**Comment by lgc2333** [comment]
可以加我详细说明下吗（联系方式在readme下面）

**Comment by YuYue-Amatsuki** [comment]
> 可以加我详细说明下吗（联系方式在readme下面）

玄学，排查了一阵子发现问题没了
