### ISSUE TITLE
读取 E:\ 占用失败

### ISSUE THREAD

**Issue by Nenot233** [lgc-NB2Dev/nonebot-plugin-picstatus#53]
```11-08 14:42:29 [ERROR] nonebot_plugin_picstatus | 读取 E:\ 占用失败
Traceback (most recent call last):
  File "D:\BOT\zhenxun_bot-dev\bot.py", line 32, in <module>
    nonebot.run()
  File "C:\Users\550N\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-36rf5U8l-py3.10\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\550N\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-36rf5U8l-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\Users\550N\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-36rf5U8l-py3.10\lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "C:\Users\550N\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-36rf5U8l-py3.10\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
    handle._run()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\BOT\zhenxun_bot-dev\zhenxun\extensive_plugin\nonebot_plugin_picstatus\collectors\__init__.py", line 82, in collect
    data = await self._get()
  File "D:\BOT\zhenxun_bot-dev\zhenxun\extensive_plugin\nonebot_plugin_picstatus\collectors\__init__.py", line 131, in _get
    return await func()
  File "D:\BOT\zhenxun_bot-dev\zhenxun\extensive_plugin\nonebot_plugin_picstatus\collectors\disk.py", line 63, in disk_usage
    usage = [x for x in map(get_one, psutil.disk_partitions()) if x]
  File "D:\BOT\zhenxun_bot-dev\zhenxun\extensive_plugin\nonebot_plugin_picstatus\collectors\disk.py", line 63, in <listcomp>
    usage = [x for x in map(get_one, psutil.disk_partitions()) if x]
> File "D:\BOT\zhenxun_bot-dev\zhenxun\extensive_plugin\nonebot_plugin_picstatus\collectors\disk.py", line 47, in get_one
    usage = psutil.disk_usage(mountpoint)
  File "C:\Users\550N\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-36rf5U8l-py3.10\lib\site-packages\psutil\__init__.py", line 2049, in disk_usage
    return _psplatform.disk_usage(path)
  File "C:\Users\550N\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-36rf5U8l-py3.10\lib\site-packages\psutil\_pswindows.py", line 291, in disk_usage
    total, free = cext.disk_usage(path)
PermissionError: [WinError 21] 设备未就绪。: 'E:\\'
```
机子是虚拟机，会一直刷这个ERROR，有解决办法吗

**Comment by Nenot233** [comment]
# 分区列表里忽略的盘符（挂载点）（可不填）
# 使用正则表达式匹配
# 由于配置项使用JSON解析，所以需要使用双反斜杠转义，
# 如："sda\\d" 解析为 sda\d（代表 sda<一位阿拉伯数字>）；
#     "C:\\\\Windows" 解析为 C:\\Windows（代表 C:\Windows）
PS_IGNORE_PARTS=[]
