### ISSUE TITLE
[bug] NotImplementedError

### ISSUE THREAD

**Issue by SZ2528** [lgc-NB2Dev/nonebot-plugin-picstatus#56]
```shell
12-16 12:32:53 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_htmlrender"
12-16 12:32:55 [INFO] nonebot_plugin_htmlrender | Browser Starting.
Task exception was never retrieved
future: <Task finished name='Task-410' coro=<Connection.run() done, defined at D:\bo\.venv\lib\site-packages\playwright\_impl\_connection.py:272> exception=NotImplementedError()>
Traceback (most recent call last):
  File "D:\bo\.venv\lib\site-packages\playwright\_impl\_connection.py", line 279, in run
    await self._transport.connect()
  File "D:\bo\.venv\lib\site-packages\playwright\_impl\_transport.py", line 133, in connect
    raise exc
  File "D:\bo\.venv\lib\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1681, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
12-16 12:32:55 [ERROR] uvicorn | Traceback (most recent call last):
  File "D:\bo\.venv\lib\site-packages\starlette\routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "D:\bo\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 155, in _lifespan_manager
    await self._lifespan.startup()
  File "D:\bo\.venv\lib\site-packages\nonebot\internal\driver\_lifespan.py", line 66, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "D:\bo\.venv\lib\site-packages\nonebot\internal\driver\_lifespan.py", line 55, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "D:\bo\.venv\lib\site-packages\nonebot_plugin_htmlrender\__init__.py", line 40, in init
    return await init_browser(**kwargs)
  File "D:\bo\.venv\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 33, in init_browser
    return await start_browser(**kwargs)
  File "D:\bo\.venv\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 63, in start_browser
    _playwright = await async_playwright().start()
  File "D:\bo\.venv\lib\site-packages\playwright\async_api\_context_manager.py", line 51, in start
    return await self.__aenter__()
  File "D:\bo\.venv\lib\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
  File "D:\bo\.venv\lib\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1681, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

12-16 12:32:55 [ERROR] uvicorn | Application startup failed. Exiting.
```

**Comment by lgc2333** [comment]
https://nonebot.dev/docs/advanced/driver#fastapi_reload
